name: Build and Validate ML Model

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    name: Execute Model Training and Validation
    runs-on: self-hosted

    defaults:
      run:
        working-directory: Chatbot

    steps:
    - name: Initialize Workspace
      run: |
        echo "Cleaning runner workspace..."
        rm -rf "$GITHUB_WORKSPACE"/*
        echo "Workspace cleaned"

    - name: Retrieve Source Code
      uses: actions/checkout@v3

    - name: Set Up Environment and Train Model
      run: |
        python -m venv build_env
        source build_env/bin/activate
        pip install -r requirements_build.txt --break-system-packages
        python3 src/run_pipelines.py

    - name: Verify Model Artifact
      id: check_model_file
      uses: andstor/file-existence-action@v1
      with:
        files: models/saved_models/disease_classification_model.pkl

    - name: Confirm Model Build Success
      if: steps.check_model_file.outputs.files_exists == 'true'
      run: echo "Model file exists! Build is successful."
