name: Build and Validate ML Model

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    name: Execute Model Training and Validation
    runs-on: self-hosted

    env:
      EC2_USER: ec2-user
      
    defaults:
      run:
        working-directory: Chatbot

    steps:
    - name: Initialize Workspace
      run: |
        echo "Cleaning runner workspace..."
        rm -rf "$GITHUB_WORKSPACE"/*
        echo "Workspace cleaned"

    - name: Retrieve Source Code
      uses: actions/checkout@v3

    - name: Set Up Environment and Train Model
      run: |
        python -m venv build_env
        source build_env/bin/activate
        pip install -r requirements_build.txt --break-system-packages
        python3 src/run_pipelines.py

    - name: Verify Model Artifact
      id: check_model_file
      run: |
        MODEL_PATH="models/saved_models/disease_classification_model.pkl"
        if [ -f "$MODEL_PATH" ]; then
          FILE_SIZE=$(stat -c%s "$MODEL_PATH")
          echo "file_exists=true" >> $GITHUB_OUTPUT
          echo "Model file exists at: $MODEL_PATH"
          echo "Model file size: $FILE_SIZE bytes"
        else
          echo "file_exists=false" >> $GITHUB_OUTPUT
          echo "Model file NOT found at: $MODEL_PATH"
          exit 1
        fi

    - name: Confirm Model Build Success
      if: steps.check_model_file.outputs.file_exists == 'true'
      run: echo "Model file exists! Build is successful."



    - name: Validate required files
      run: |
          REQUIRED_FILES=(
            web_app/app.py
            web_app/app_data/symptoms.json
            web_app/app_data/treatments.json
            web_app/app_data/condition_patterns.json
            web_app/app_data/symptom_batches.json
            web_app/templates/index.html
            models/saved_models/disease_classification_model.pkl
            requirements_deploy.txt
            web_app/config/gunicorn_config.py
            config/nginx.conf
            web_app/start.sh
            web_app/stop.sh
            nginx_setup.sh
            run_chatbot.py
            setup.sh
            set.sh
          )
          echo "[INFO] Validating required files..."
          for FILE in "${REQUIRED_FILES[@]}"; do
            if [ ! -f "$FILE" ]; then
              echo "[ERROR] Missing required file: $FILE"
              exit 1
            else
              echo "[OK] Found: $FILE"
            fi
          done

    - name: Zip minimal app contents
      run: |
          mkdir -p dist/mlchatbot-app
          mkdir -p dist/mlchatbot-app/models/saved_models
          cp -rf web_app dist/mlchatbot-app/
          cp models/saved_models/disease_classification_model.pkl dist/mlchatbot-app/models/saved_models/
          cp requirements_deploy.txt dist/mlchatbot-app/
          cp -rf config dist/mlchatbot-app/
          cp set.sh dist/mlchatbot-app/
          cp setup.sh dist/mlchatbot-app/
          cp nginx_setup.sh dist/mlchatbot-app/
          cp run_chatbot.py dist/mlchatbot-app/
          cd dist && zip -r mlchatbot-app.zip mlchatbot-app

    - name: Read Hostname from File
      id: read-hostname
      run: |
          EC2_HOST=$(cat /tmp/ec2_host.txt)
          echo "EC2_HOST=$EC2_HOST" >> $GITHUB_ENV
          echo "Read EC2_HOST from /tmp/ec2_host.txt: $EC2_HOST"

    - name: Upload App to EC2
      run: |
        scp -i ~/.ssh/mlchatbot_app_key.pem -o StrictHostKeyChecking=no dist/mlchatbot-app.zip "$EC2_USER@${{ env.EC2_HOST }}:~/"


    - name: Deploy App on EC2
      run: |
          ssh -i ~/.ssh/mlchatbot_app_key.pem -o StrictHostKeyChecking=no \
            "$EC2_USER@${{ env.EC2_HOST }}" << 'EOF'
              rm -rf mlchatbot-app
              unzip -o mlchatbot-app.zip
              cd mlchatbot-app
              sudo chmod 755 web_app/*.sh
              sudo chmod 755 set.sh
              sudo chmod 755 nginx_setup.sh
              sudo chmod 755 setup.sh
          EOF


    - name: Deploy
      run: |
          ssh -i ~/.ssh/mlchatbot_app_key.pem -o StrictHostKeyChecking=no \
            "$EC2_USER@${{ env.EC2_HOST }}" << 'EOF'
              cd mlchatbot-app
              sudo chmod 755 setup.sh
              sudo chmod 755 nginx_setup.sh
          EOF
