name: Build and Validate ML Model

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    name: Execute Model Training and Validation
    runs-on: self-hosted

    defaults:
      run:
        working-directory: Chatbot

    steps:
    - name: Initialize Workspace
      run: |
        echo "Cleaning runner workspace..."
        rm -rf "$GITHUB_WORKSPACE"/*
        echo "Workspace cleaned"

    - name: Retrieve Source Code
      uses: actions/checkout@v3

    - name: Set Up Environment and Train Model
      run: |
        python -m venv build_env
        source build_env/bin/activate
        pip install -r requirements_build.txt --break-system-packages
        python3 src/run_pipelines.py

    - name: Verify Model Artifact
      id: check_model_file
      run: |
        MODEL_PATH="models/saved_models/disease_classification_model.pkl"
        if [ -f "$MODEL_PATH" ]; then
          FILE_SIZE=$(stat -c%s "$MODEL_PATH")
          echo "file_exists=true" >> $GITHUB_OUTPUT
          echo "Model file exists at: $MODEL_PATH"
          echo "Model file size: $FILE_SIZE bytes"
        else
          echo "file_exists=false" >> $GITHUB_OUTPUT
          echo "Model file NOT found at: $MODEL_PATH"
          exit 1
        fi

    - name: Confirm Model Build Success
      if: steps.check_model_file.outputs.file_exists == 'true'
      run: echo "Model file exists! Build is successful."


      
